@url =  https://4nflpr3gl5.execute-api.us-east-1.amazonaws.com/dev

###
GET {{url}}/todos/list

###
POST {{url}}/todos
Content-Type: application/json

{
    "todo": "practice REACT"
}

###
GET {{url}}/todos/54acd9a3-7ac9-4054-8369-b25a311c73ad