@url =  https://4nflpr3gl5.execute-api.us-east-1.amazonaws.com/dev

###
GET {{url}}/todos/list

###
POST {{url}}/todos
Content-Type: application/json

{
    "todo": "learn AWS"
}

###
GET {{url}}/todos/64c50ad5-5881-4810-b2af-86e56848f0bf

###
DELETE {{url}}/todos/64c50ad5-5881-4810-b2af-86e56848f0bf

###
PATCH {{url}}/todos/ec205f77-d50e-4ebd-aae7-774d09412d04
Content-Type: application/json

{
   "checked": true,
   "todo": "learn Serverless Framework"
}